server.port=8080
app.base-url=http://192.168.1.2:8080


# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/anu_construction
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Admin Credentials
admin.username=admin
admin.password=admin123

# File Upload Configuration
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

